# Generated by Django 4.2.3 on 2023-08-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=50)),
                ('Job_post', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('stipend', models.IntegerField()),
                ('job_description', models.CharField(max_length=1000)),
                ('requirements', models.CharField(max_length=200)),
            ],
        ),
    ]
